//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vSlide.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string nextLevelKey {
            get {
                return ((string)(this["nextLevelKey"]));
            }
            set {
                this["nextLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string prevLevelKey {
            get {
                return ((string)(this["prevLevelKey"]));
            }
            set {
                this["prevLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string incrSliderKey {
            get {
                return ((string)(this["incrSliderKey"]));
            }
            set {
                this["incrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string decrSliderKey {
            get {
                return ((string)(this["decrSliderKey"]));
            }
            set {
                this["decrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string controlModNextLevelKey {
            get {
                return ((string)(this["controlModNextLevelKey"]));
            }
            set {
                this["controlModNextLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string controlModPrevLevelKey {
            get {
                return ((string)(this["controlModPrevLevelKey"]));
            }
            set {
                this["controlModPrevLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string controlModIncrSliderKey {
            get {
                return ((string)(this["controlModIncrSliderKey"]));
            }
            set {
                this["controlModIncrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string controlModDecrSliderKey {
            get {
                return ((string)(this["controlModDecrSliderKey"]));
            }
            set {
                this["controlModDecrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string shiftModNextLevelKey {
            get {
                return ((string)(this["shiftModNextLevelKey"]));
            }
            set {
                this["shiftModNextLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string shiftModPrevLevelKey {
            get {
                return ((string)(this["shiftModPrevLevelKey"]));
            }
            set {
                this["shiftModPrevLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string shiftModIncrSliderKey {
            get {
                return ((string)(this["shiftModIncrSliderKey"]));
            }
            set {
                this["shiftModIncrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string shiftModDecrSliderKey {
            get {
                return ((string)(this["shiftModDecrSliderKey"]));
            }
            set {
                this["shiftModDecrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string altModNextLevelKey {
            get {
                return ((string)(this["altModNextLevelKey"]));
            }
            set {
                this["altModNextLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string altModPrevLevelKey {
            get {
                return ((string)(this["altModPrevLevelKey"]));
            }
            set {
                this["altModPrevLevelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string altModIncrSliderKey {
            get {
                return ((string)(this["altModIncrSliderKey"]));
            }
            set {
                this["altModIncrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string altModDecrSliderKey {
            get {
                return ((string)(this["altModDecrSliderKey"]));
            }
            set {
                this["altModDecrSliderKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int keySetupRadioButton {
            get {
                return ((int)(this["keySetupRadioButton"]));
            }
            set {
                this["keySetupRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int levelKeysOnlyRadioButton {
            get {
                return ((int)(this["levelKeysOnlyRadioButton"]));
            }
            set {
                this["levelKeysOnlyRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useHoldDownBothKeysChecked {
            get {
                return ((bool)(this["useHoldDownBothKeysChecked"]));
            }
            set {
                this["useHoldDownBothKeysChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int pressTresholdHoldLevelLPNumericUpDown {
            get {
                return ((int)(this["pressTresholdHoldLevelLPNumericUpDown"]));
            }
            set {
                this["pressTresholdHoldLevelLPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int tickIntervalHoldLevelLPNumericUpDown {
            get {
                return ((int)(this["tickIntervalHoldLevelLPNumericUpDown"]));
            }
            set {
                this["tickIntervalHoldLevelLPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int pressTresholdHoldSliderLPNumericUpDown {
            get {
                return ((int)(this["pressTresholdHoldSliderLPNumericUpDown"]));
            }
            set {
                this["pressTresholdHoldSliderLPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int tickIntervalHoldSliderLPNumericUpDown {
            get {
                return ((int)(this["tickIntervalHoldSliderLPNumericUpDown"]));
            }
            set {
                this["tickIntervalHoldSliderLPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int sliderDeltaHoldSliderLPNumericUpDown {
            get {
                return ((int)(this["sliderDeltaHoldSliderLPNumericUpDown"]));
            }
            set {
                this["sliderDeltaHoldSliderLPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int pressTresholdLevelSystemBPNumericUpDown {
            get {
                return ((int)(this["pressTresholdLevelSystemBPNumericUpDown"]));
            }
            set {
                this["pressTresholdLevelSystemBPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int tickIntervalLevelSystemBPNumericUpDown {
            get {
                return ((int)(this["tickIntervalLevelSystemBPNumericUpDown"]));
            }
            set {
                this["tickIntervalLevelSystemBPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int tickIntervalSliderSystemBPNumericUpDown {
            get {
                return ((int)(this["tickIntervalSliderSystemBPNumericUpDown"]));
            }
            set {
                this["tickIntervalSliderSystemBPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int sliderDeltaSliderSystemBPNumericUpDown {
            get {
                return ((int)(this["sliderDeltaSliderSystemBPNumericUpDown"]));
            }
            set {
                this["sliderDeltaSliderSystemBPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int tickIntervalSPNumericUpDown {
            get {
                return ((int)(this["tickIntervalSPNumericUpDown"]));
            }
            set {
                this["tickIntervalSPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170")]
        public int sliderDeltaSPNumericUpDown {
            get {
                return ((int)(this["sliderDeltaSPNumericUpDown"]));
            }
            set {
                this["sliderDeltaSPNumericUpDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 1")]
        public string sliderLevelsAbsolute {
            get {
                return ((string)(this["sliderLevelsAbsolute"]));
            }
            set {
                this["sliderLevelsAbsolute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0;100")]
        public string sliderLevelsRelative {
            get {
                return ((string)(this["sliderLevelsRelative"]));
            }
            set {
                this["sliderLevelsRelative"] = value;
            }
        }
    }
}
